<a class="headline" href="<?php echo $data['story']['url'] ?>"><?php echo  $data['story']['headline'] ?></a><br />
<span class="details"><?php echo $data['story']['created_by'] ?> | <?php echo $data['comment_count'] ?> Comments | 
<?php echo date('n/j/Y g:i a', strtotime($data['story']['created_on'])) ?></span>


<?php if($data['authenticated']) { ?>
<form method="post" action="/comment/create">
<input type="hidden" name="story_id" value="<?php echo $data['story_id'] ?>" />
<textarea cols="60" rows="6" name="comment"></textarea><br />
<input type="submit" name="submit" value="Submit Comment" />
</form>
<?php } ?>

<?php

foreach($data['comments'] as $comment) {
    print('
        <div class="comment"><span class="comment_details">' . $comment['created_by'] . ' | ' .
        date('n/j/Y g:i a', strtotime($comment['created_on'])) . '</span>
        ' . $comment['comment'] . '</div>
    ');
}

?>