<?php echo $data['error'] ?><br />

<label>Username:</label><?php echo $data['username'] ?><br />
<label>Email:</label><?php echo $data['email'] ?><br />

 <form method="post">
    <label>Password</label> <input type="password" name="password" value="" /><br />
    <label>Password Again</label> <input type="password" name="password_check" value="" /><br />
    <input type="submit" name="updatepw" value="Create User" />
</form>